# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "SP6MI"
description: > # this means to ignore newlines until "email:"
   Krótkofalarstwo i projekty IT

email: sp6mi@proton.me
#blog logo


# blog cover
cover: "/assets/images/ic7410-2.jpg"

name: 'Marcin I'
author: 'Marcin I'
# author_image: "/assets/images/author.jpg"

paginate:	5

url: "darvark.github.io" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards

# social icons and sharing options
social:
  - icon:	github
    url:	https://github.com/darvark
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:
