title:              Radiosport
email:              zawody@pzk.org.pl
description:        Polski Związek Krótkofalowców
author:             Polski Związek Krótkofalowców
baseurl:            "/"
url:                "https://sport.pzk.org.pl"

# Social Profiles
facebook_username:  PolskiZwiazekKrotkofalowcow

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
