name: Jekyll site CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"

  deploy:
    needs: ['build']
    runs-on: ubuntu-latest
    steps:
    - name: ftp-action
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.OVH_FTP }}
        username: ${{ secrets.OVH_USER }}
        password: ${{ secrets.OVH_PASS }}
        protocol: ftp
        port: 21 # todo replace with your web host
        server-dir: www/
