name: Jekyll site CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the site in the jekyll/builder container
      run: |
        sudo apt install gcc,g++,make,openssl-dev,libc-dev,ruby,ruby-dev,ruby-bundler,ruby-json; \
        bundle install --deployment; \
        bundle exec jekyll doctor; \
        bundle exec jekyll build
        
        # docker run \
        # -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        # jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"

    - name: Rem old artifact
      run: rm -rf /home/runner/work/strona.tgz
      
    - name: Archive
      run: tar -cvzf /home/runner/work/strona.tgz ${{ github.workspace }}

    - name: Artifact
      uses: actions/upload-artifact@v2
      with:
        name: strona
        path: /home/runner/work/strona.tgz

  deploy:
    needs: ['build']
    runs-on: ubuntu-latest
    steps:
    - name: Install lftp
      run: |
        sudo apt install lftp -y
    
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: strona

    - name: Extract
      run: tar zxvf strona.tgz --strip-components 5

    - name: ftp-action
      uses: pressidium/lftp-mirror-action@v1
      with:
        # SFTP credentials
        host: ${{ secrets.OVH_FTP }}
        user: ${{ secrets.OVH_USER }}
        pass: ${{ secrets.OVH_PASS }}
        # lftp settings
        onlyNewer: true
        settings: 'sftp:auto-confirm=yes'
        # Mirror command options
        localDir: '.'
        remoteDir: 'www/'
        reverse: true
        ignoreFile: '.git'
        options: '--verbose'
      
      # uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      # with:
      #   server: ${{ secrets.OVH_FTP }}
      #   username: ${{ secrets.OVH_USER }}
      #   password: ${{ secrets.OVH_PASS }}
      #   protocol: ftp
      #   port: 21 # todo replace with your web host
      #   server-dir: www/

