name: Jekyll site CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"

    - name: Rem old artifact
      run: rm -rf /home/runner/work/strona.zip
      
    - name: Archive
      run: zip /home/runner/work/strona.tgz ${{ github.workspace }}

    - name: Artifact
      uses: actions/upload-artifact@v2
      with:
        name: strona
        path: /home/runner/work/strona.zip

  deploy:
    needs: ['build']
    runs-on: ubuntu-latest
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: strona

    - name: Extract
      run: unzip -j strona.zip

    - name: ftp-action
      run: lftp -u ${{ secrets.OVH_USER }},${{ secrets.OVH_PASS }} -c "
          open ${{ secrets.OVH_FTP }} &&
          cd www/ &&
          mirror -R --delete -v" 
      # uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      # with:
      #   server: ${{ secrets.OVH_FTP }}
      #   username: ${{ secrets.OVH_USER }}
      #   password: ${{ secrets.OVH_PASS }}
      #   protocol: ftp
      #   port: 21 # todo replace with your web host
      #   server-dir: www/
      #   local-dir: ${{ github.workspace }}/
